### ISSUE TITLE
[Bug]: Can't Make Page Create A publicly accessible page

### ISSUE THREAD

**Issue by scryba** [tobiasla78/filament-simple-pages#4]
### What happened?

needed to create a public page http://localhost/page/privacy-policy  but it creates http://localhost/admin/page/privacy-policy.  

/admin is a protected page

### How to reproduce the bug

.

### Package Version

0.4.1

### PHP Version

8.2.0

### Laravel Version

10.47.0

### Which operating systems does with happen with?

Linux

**Comment by tobiasla78** [comment]
Thanks for reporting this.

It's not really a bug it was intended to be publicy viewable if the second panel is public.
But anyway I fully agree it should also acessable outside Filament panels.

I will add this feature in time.

**Comment by scryba** [comment]
That will be great, maybe add an option like 'detached from panel'  in the Additional Configuration.

**Comment by tobiasla78** [comment]
Now added in v1.0.0. Thanks!
